name: release

on:
  push:
    paths:
      - 'release-versions/*'
              
  workflow_dispatch:
  
permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Read VERSION file
        id: getversion
        run: echo "::set-output name=version::$(cat release-versions/swagger-ui-latest.txt)"
        
      - name: Fetch release version
        run: |
          echo "::set-output name=version::$(\
          curl -sL https://api.github.com/repos/Schievel1/testebase/releases/latest | \
          jq -r ".tag_name")"
          
      - uses: actions/checkout@v3.3.0
        with:
          repository: an-anime-team/an-anime-game-launcher
          submodules: true
          ref: ${{ steps.getversion.outputs.version }}

      - name: Create zip
        run: |
          cd ..
          zip ${{ github.event.repository.name }}/${{ github.event.repository.name }}-release-tarball.zip ${{ github.event.repository.name }} -r
          echo "from auto release tag: $(cat release-versions/swagger-ui-latest.txt)"
          
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ steps.getversion.outputs.version }}
          prerelease: true
          files: |
            ${{ github.event.repository.name }}-release-tarball.zip

