name: release

on:
  push:
    paths:
      - 'release-versions/*'
              
  workflow_dispatch:
  
permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch release version
        run: |
          echo "latest_tag=$(\
          curl -sL https://api.github.com/repos/Schievel1/testebase/releases/latest | \
          jq -r ".tag_name")" >> $GITHUB_ENV
          
      - uses: actions/checkout@v3.3.0
        with:
          repository: an-anime-team/an-anime-game-launcher
          submodules: true
          ref: ${{ env.latest_tag }}
          
      - name: Checkout anime-game-core
        uses: actions/checkout@v3.3.0
        with:
          repository: an-anime-team/anime-game-core
          path: anime-launcher-sdk/anime-game-core
          ref: 'main'

      - name: Create zip
        run: |
          cd ..
          zip aagl-${{ env.latest_tag }}-complete.zip ${{ github.event.repository.name }} -r
          tar -czvf aagl-${{ env.latest_tag }}-complete.tar.gz ${{ github.event.repository.name }}
          
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ env.latest_tag }}
          prerelease: true
          files: |
            ../aagl-${{ env.latest_tag }}-complete.zip
            ../aagl-${{ env.latest_tag }}-complete.tar.gz

