name: release

on:
  push:
    paths:
      - 'release-versions/*'
              
  workflow_dispatch:
  
permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch release version
        run: |
          echo "latest_tag=1.0.2" >> $GITHUB_ENV
          echo "::set-output name=version::$(\
          curl -sL https://api.github.com/repos/Schievel1/testebase/releases/latest | \
          jq -r ".tag_name")"
          echo "$(\
          curl -sL https://api.github.com/repos/Schievel1/testebase/releases/latest | \
          jq -r ".tag_name")"
          
      - uses: actions/checkout@v3.3.0
        with:
          repository: an-anime-team/an-anime-game-launcher
          submodules: true
          ref: ${{ env.latest_tag }}

      - name: Create zip
        run: |
          cd ..
          zip ${{ github.event.repository.name }}/${{ github.event.repository.name }}-release-tarball.zip ${{ github.event.repository.name }} -r
          echo "from auto release tag: ${{ env.latest_tag }}"
          
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ env.latest_tag }}
          prerelease: true
          files: |
            ${{ github.event.repository.name }}-release-tarball.zip

